/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.4
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using SitefinityWebApp.TorrentTrackerServices;
using SitefinityWebApp.TorrentTrackerServices.Contracts;
using SitefinityWebApp.TorrentTrackerServices.Dtos;
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SitefinityWebApp.Mvc.Controllers
{
    [ControllerToolboxItem(Name = "CreateTorrentWidget_MVC", Title = "Create Torrent", SectionName = "Create torrents")]
    public class CreateTorrentWidgetController : Controller
    {
        private readonly ITorrentService _torrentService;
        private readonly ITaxonomyService _taxonomyService;

        public CreateTorrentWidgetController(ITorrentService torrentService,
            ITaxonomyService taxonomyService)
        {
            _torrentService = torrentService;
            _taxonomyService = taxonomyService;
        }

        public ActionResult Index()
        {
            CreateTorrentWidgetModel model = CreateInitialTorrentWidgetModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(CreateTorrentWidgetModel model)
        {
            if (!ValidateModel(model))
            {
                // quickfix to populate genres when invalid data is passed on Add torrent
                var genres = _taxonomyService.GetTaxonNamesByTaxonomy(Constants.GenresTaxonomyName);
                model.Genres = genres;
                return View(model);
            }

            StringBuilder sb = new StringBuilder();
            try
            {
                CreateTorrentDto torrent = DtoCreator.CreateTorrent(model);
                _torrentService.CreateTorrentWithPublish(torrent);

                sb.AppendLine(string.Format(Constants.CreateTorrentSuccessMessage, model.Title));
                ViewBag.SuccessMessage = sb.ToString();
            }
            catch (Exception exc)
            {
                sb.AppendLine(exc.Message);

                if (exc.InnerException != null)
                {
                    sb.AppendLine(exc.InnerException.Message);
                }

                ViewBag.ErrorMessage = sb.ToString();
            }

            return View(CreateInitialTorrentWidgetModel());
        }

        private CreateTorrentWidgetModel CreateInitialTorrentWidgetModel()
        {
            var genres = _taxonomyService.GetTaxonNamesByTaxonomy(Constants.GenresTaxonomyName);
            return new CreateTorrentWidgetModel()
            {
                Genres = genres
            };
        }

        private bool ValidateModel(CreateTorrentWidgetModel model)
        {
            if (!ModelState.IsValid)
            {
                return false;
            }

            bool result = true;

            string imageFileExtension = Path.GetExtension(model.UserImageData.FileName).ToLower();
            if (!Constants.ValidImageFiles.Contains(imageFileExtension))
            {
                ModelState.AddModelError(
                    nameof(CreateTorrentWidgetModel.UserImageData),
                    string.Format(Constants.InvalidFileFormatMessage, imageFileExtension, Constants.ImageText, string.Join("; ", Constants.ValidImageFiles)));

                result = false;
            }

            string documentFileExtension = Path.GetExtension(model.UserTorrentData.FileName).ToLower();
            if (!Constants.ValidDocumentFiles.Contains(documentFileExtension))
            {
                ModelState.AddModelError(
                    nameof(CreateTorrentWidgetModel.UserTorrentData),
                    string.Format(Constants.InvalidFileFormatMessage, documentFileExtension, Constants.TorrentText, string.Join("; ", Constants.ValidDocumentFiles)));

                result = false;
            }

            return result;
        }
    }
}